version: '3'

services:
    ui:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

    blob-storage-api:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

    metadata-processing:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

    indexing:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

    core-web-api:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

    core-backend:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

    core-frontend:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

    core-sagahost:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

    core-persistence:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

    imaging:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

    office-processor:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}
    
    microscopy-metadata-service:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}
    
    categories:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

    eventstore:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

    redis:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

    rabbitmq:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

    mongo:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

    postgres:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

    keycloak:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

    elasticsearch:
        logging:
            driver: awslogs
            options:
                awslogs-region: ${AWS_REGION}
                awslogs-group: ${AWS_LOG_GROUP}

networks:
    leanda-ext:
        external:
            name: leanda-net
