version: '3'

services:
    blob-storage-api:
        container_name: blob-storage-api
        entrypoint: /bin/bash
        image: leanda/blob-storage-webapi:${TAG_VERSION-latest}
        environment:
        - IDENTITY_SERVER_URL=${IDENTITY_SERVER_URL}
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.Storage.Blob.WebApi
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "18006:18006"
        depends_on:
        - rabbitmq
        - mongo

    metadata-processing:
        container_name: metadata-processing
        image: leanda/metadata-processing:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.MetadataStorage.Processing
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11050:11050"
        depends_on:
        - rabbitmq

    indexing:
        container_name: indexing
        image: leanda/indexing:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_ES=http://elasticsearch:9200
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.Indexing
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11090:11090"
        depends_on:
        - rabbitmq

    core-web-api:
        container_name: core-web-api
        image: leanda/core-web-api:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - IDENTITY_SERVER_URL=${IDENTITY_SERVER_URL}
        - OSDR_REDIS=redis
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_EVENT_STORE=ConnectTo=tcp://admin:changeit@eventstore:1113
        - OSDR_ES=http://elasticsearch:9200
        - OSDR_LOG_LEVEL=${OSDR_LOG_LEVEL}
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.Osdr.WebApi
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "28611:18006"
        depends_on:
        - rabbitmq
        - eventstore
        - redis
        - mongo

    core-backend:
        container_name: core-backend
        image: leanda/core-backend:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_EVENT_STORE=ConnectTo=tcp://admin:changeit@eventstore:1113
        - OSDR_REDIS=redis
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.Osdr.Domain.BackEnd
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11030:11030"
        depends_on:
        - rabbitmq
        - eventstore
        - redis
        - mongo

    core-frontend:
        container_name: core-frontend
        image: leanda/core-frontend:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_EVENT_STORE=ConnectTo=tcp://admin:changeit@eventstore:1113
        - OSDR_REDIS=redis
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.Osdr.Domain.FrontEnd
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11020:11020"

    core-sagahost:
        container_name: core-sagahost
        image: leanda/core-sagahost:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.Osdr.Domain.SagaHost
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11010:11010"
        depends_on:
        - rabbitmq
        - mongo

    core-persistence:
        container_name: core-persistence
        image: leanda/core-persistence:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.Osdr.Persistence
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11000:11000"
        depends_on:
        - rabbitmq
        - mongo

    imaging:
        container_name: imaging
        image: leanda/imaging:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - QUEUE_PREFETCH_SIZE=9
        - EXECUTOR_THREAD_COUNT=3
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- java -Djava.awt.headless=true -Xmx256m -XX:NativeMemoryTracking=summary -jar sds-imaging-service.jar
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        - ${OSDR_TEMP_FILES_FOLDER}:/temp
        networks:
        - leanda-ext
        depends_on:
        - rabbitmq
        - mongo

    office-processor:
        container_name: office-processor
        image: leanda/office-file-processor:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - TZ=EST
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - QUEUE_PREFETCH_SIZE=9
        - EXECUTOR_THREAD_COUNT=2
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./wait-for-it.sh mongo:27017 -t 60 -- java -XX:NativeMemoryTracking=summary -jar office-file-processor.jar
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        - ${OSDR_TEMP_FILES_FOLDER}:/temp
        ports:
        - 8987:8087
        networks:
        - leanda-ext
        depends_on:
        - rabbitmq
        - mongo
    
    microscopy-metadata-service:
        container_name: microscopy-metadata
        image: leanda/microscopy-metadata:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - TZ=EST
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - QUEUE_PREFETCH_SIZE=9
        - EXECUTOR_THREAD_COUNT=3
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./wait-for-it.sh mongo:27017 -t 60 -- java -XX:NativeMemoryTracking=summary -jar leanda-microscopy-metadata-service.jar
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs/
        - ${OSDR_TEMP_FILES_FOLDER}:/temp/
        ports:
        - 8986:8090
        networks:
        - leanda-ext
        depends_on:
        - rabbitmq
        - mongo

    categories: 
        container_name: categories
        image: leanda/categories-service:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment: 
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - OSDR_ES=http://elasticsearch:9200
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./wait-for-it.sh mongo:27017 -t 60 -- ./wait-for-it.sh elasticsearch:9200 -t 60 -- ./Leanda.Categories.Processing
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        - ${OSDR_TEMP_FILES_FOLDER}:/temp
        networks:
        - leanda-ext
        depends_on:
        - rabbitmq  
        - mongo
        - elasticsearch

    eventstore:
        image: eventstore/eventstore:release-4.0.2
        container_name: eventstore
        ports:
        - "2113:2113"
        - "1113:1113"
        environment:
        - RUN_PROJECTIONS=All
        volumes:
        - data-eventstore:/var/lib/eventstore
        networks:
        - leanda-ext

    redis:
        image: redis:4-alpine
        container_name: redis
        command: redis-server --appendonly yes
        ports:
        - "6379:6379"
        volumes:
        - data-redis:/data
        networks:
        - leanda-ext

    rabbitmq:
        image: leanda/rabbitmq
        container_name: rabbitmq
        hostname: "rabbitmq-dev"
        environment:
        - RABBITMQ_DEFAULT_VHOST=osdr_dev
        ports:
        - "8282:15672"
        - "5671:5671"
        - "5672:5672"
        volumes:
        - data-rabbitmq:/var/lib/rabbitmq
        networks:
        - leanda-ext

    mongo:
        image: mongo:3.6
        container_name: mongo
        ports:
        - "27017:27017"
        volumes:
        - data-mongo-config:/data/configdb
        - data-mongo-data:/data/db
        networks:
        - leanda-ext

    elasticsearch:
        image: leanda/elasticsearch
        container_name: elasticsearch
        environment:
        - discovery.type=single-node
        volumes:
        - data-elasticsearch:/usr/share/elasticsearch/data
        ports:
        - "9201:9201"
        - "9200:9200"
        - "9301:9300"
        networks:
        - leanda-ext

volumes:
    data-eventstore:
    data-redis:
    data-rabbitmq:
    data-elasticsearch:
    data-mongo-config:
    data-mongo-data:

networks:
    leanda-ext:
        external:
            name: leanda-net
