version: '3'

services:
    core-persistence:
        image: leanda/core-persistence:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo.${AWS_NAMESPACE}:27017/osdr_dev
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq.${AWS_NAMESPACE}:5672/osdr_dev
        command: ./wait-for-it.sh rabbitmq.${AWS_NAMESPACE}:5672 -t 60 -- ./Sds.Osdr.Persistence
      
        ports:
        - "11000:11000"
        logging:
            driver: awslogs
            options: 
                awslogs-group: ${AWS_LOG_GROUP}
                awslogs-region: ${AWS_REGION}
                awslogs-stream-prefix: core-persistence
