version: '3'

services:
    core-frontend:
      image: leanda/core-frontend:${TAG_VERSION-latest}
      entrypoint: /bin/bash
      environment:
      - OSDR_LOG_FOLDER=/logs
      - OSDR_MONGO_DB=mongodb://mongo.leanda:27017/osdr_dev
      - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq.leanda:5672/osdr_dev
      - OSDR_EVENT_STORE=ConnectTo=tcp://admin:changeit@eventstore.leanda:1113
      - OSDR_REDIS=redis
      command: ./wait-for-it.sh rabbitmq.leanda:5672 -t 60 -- ./Sds.Osdr.Domain.FrontEnd
      ports:
      - "11020:11020"
      logging:
          driver: awslogs
          options: 
              awslogs-group: ${AWS_LOG_GROUP}
              awslogs-region: ${AWS_REGION}
              awslogs-stream-prefix: core-frontend
