version: '3'

services:
    mongo:
        image: mongo:3.6
        logging:
            driver: awslogs
            options:
                awslogs-group: leanda
                awslogs-region: us-east-1
                awslogs-stream-prefix: mongo
        ports:
        - "27017:27017"
        volumes:
        - data-mongo-config:/data/configdb
        - data-mongo-data:/data/db

    blob-storage-api:
        entrypoint: /bin/bash
        image: leanda/blob-storage-webapi:${TAG_VERSION-latest}
        environment:
        - IDENTITY_SERVER_URL=${IDENTITY_SERVER_URL}
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - MAX_BLOB_SIZE=${MAX_BLOB_SIZE}
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.Storage.Blob.WebApi
        logging:
            driver: awslogs
            options: 
                awslogs-group: leanda
                awslogs-region: us-east-1
                awslogs-stream-prefix: blob-storage
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        ports:
        - "18006:18006"
        links:
        - mongo
        - rabbitmq

    rabbitmq:
        image: leanda/rabbitmq
        environment:
        - RABBITMQ_DEFAULT_VHOST=osdr_dev
        logging:
            driver: awslogs
            options: 
                awslogs-group: leanda
                awslogs-region: us-east-1
                awslogs-stream-prefix: rabbit
        ports:
        - "8282:15672"
        - "5671:5671"
        - "5672:5672"
        volumes:
        - data-rabbitmq:/var/lib/rabbitmq

volumes:
    data-mongo-config:
    data-mongo-data:
    data-rabbitmq:
