version: '3'

services:
   

    mongo:
        image: mongo:3.6
        ports:
        - "27017:27017"
        volumes:
        - data-mongo-config:/data/configdb
        - data-mongo-data:/data/db
        logging:
            driver: awslogs
            options: 
                awslogs-group: ${AWS_LOG_GROUP}
                awslogs-region: ${AWS_REGION}
                awslogs-stream-prefix: mongo

volumes:
    # data-eventstore:
    # data-redis:
    # data-rabbitmq:
  # data-elasticsearch:
    data-mongo-config:
    data-mongo-data:
# #     data-pstgresql:
