version: '3'

services:
    reaction-parser:
        image: leanda/reaction-file-parser:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - TZ=EST
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq.${AWS_NAMESPACE}:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo.${AWS_NAMESPACE}:27017/osdr_dev
        - QUEUE_PREFETCH_SIZE=9
        - EXECUTOR_THREAD_COUNT=3
        command: ./wait-for-it.sh rabbitmq.${AWS_NAMESPACE}:5672 -t 60 -- ./wait-for-it.sh mongo.${AWS_NAMESPACE}:27017 -t 60 -- java -XX:NativeMemoryTracking=summary -jar reaction-parser.jar

        logging:
            driver: awslogs
            options: 
                awslogs-group: ${AWS_LOG_GROUP}
                awslogs-region: ${AWS_REGION}
                awslogs-stream-prefix: reaction-parser
