version: '3'

services:
    metadata-processing:
        image: leanda/metadata-processing:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo.${AWS_NAMESPACE}:27017/osdr_dev
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq.${AWS_NAMESPACE}:5672/osdr_dev
        command: ./wait-for-it.sh rabbitmq.${AWS_NAMESPACE}:5672 -t 60 -- ./Sds.MetadataStorage.Processing
        ports:
        - "11050:11050"
        logging:
            driver: awslogs
            options: 
                awslogs-group: ${AWS_LOG_GROUP}
                awslogs-region: ${AWS_REGION}
                awslogs-stream-prefix: metadata-processing
