version: '3'

services:
     nginx:
        image: leanda/nginx
        environment:
        - BLOB_API=http://blob-storage-web-api.leanda:18006/
        - CORE_API=http://core-web-api.leanda:18006/
        ports:
        - "80:80"
        logging:
            driver: awslogs
            options: 
                awslogs-group: ${AWS_LOG_GROUP}
                awslogs-region: ${AWS_REGION}
                awslogs-stream-prefix: nginx
