version: '3'

services:

    elastic:
        image: leanda/elasticsearch
        environment:
        - discovery.type=single-node
        volumes:
        - data-elasticsearch:/usr/share/elasticsearch/data
        ports:
        - "9201:9201"
        - "9200:9200"
        - "9300:9300"
        logging:
            driver: awslogs
            options: 
                awslogs-group: ${AWS_LOG_GROUP}
                awslogs-region: ${AWS_REGION}
                awslogs-stream-prefix: elasticsearch

volumes:
  data-elasticsearch:

