version: '3'

services:
    categories: 
        image: leanda/categories-service:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment: 
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq.${AWS_NAMESPACE}:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo.${AWS_NAMESPACE}:27017/osdr_dev
        - OSDR_ES=http://elastic.${AWS_NAMESPACE}:9200
        command: ./wait-for-it.sh rabbitmq.${AWS_NAMESPACE}:5672 -t 60 -- ./wait-for-it.sh mongo.${AWS_NAMESPACE}:27017 -t 60 -- ./wait-for-it.sh elastic.${AWS_NAMESPACE}:9200 -t 60 -- ./Leanda.Categories.Processing

        logging:
            driver: awslogs
            options: 
                awslogs-group: ${AWS_LOG_GROUP}
                awslogs-region: ${AWS_REGION}
                awslogs-stream-prefix: categories
