version: '3'

services:
    postgres:
      container_name: 'keycloak-postgres'
      image: postgres:13.1
      environment:
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
        POSTGRES_DATABASE: keycloak
        POSTGRES_ROOT_PASSWORD: keycloak
        pgdata: data-pstgresql
      ports:
      - '5432:5432'
      volumes:
      - data-pstgresql:/var/lib/postgres
      networks:
      - leanda-ext

    keycloak:
        container_name: 'keycloak-server'
        image: leanda/keycloak:latest
        environment:
          DB_VENDOR: POSTGRES
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: keycloak
          POSTGRES_PORT_5432_TCP_ADDR: postgres
          POSTGRES_DATABASE: keycloak
          JDBC_PARAMS: 'connectTimeout=30'
        ports:
        - '80:8080'
        - '443:8443'
        volumes:
        - data-keycloak:/var/lib/keycloak
        networks:
        - leanda-ext
        depends_on:
        - postgres

volumes:
    data-keycloak:
    data-pstgresql:

networks:
    leanda-ext:
        external:
            name: leanda-net
