version: '3'

services:
    postgres:
      container_name: 'keycloak-postgres'
      image: postgres:13.1
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DATABASE: ${POSTGRES_USER}
        POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
        pgdata: data-pstgresql
      ports:
      - '5432:5432'
      volumes:
      - data-pstgresql:/var/lib/postgres
      networks:
      - leanda-ext

    keycloak:
        container_name: 'keycloak-server'
        image: leanda/keycloak:latest
        environment:
          DB_ADDR: postgres
          DB_USER: ${POSTGRES_USER}
          DB_PASSWORD: ${POSTGRES_PASSWORD}           
          DB_VENDOR: POSTGRES
          DB_DATABASE: ${POSTGRES_USER}
          KEYCLOAK_USER: ${KEYCLOAK_USER}
          KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
          JDBC_PARAMS: 'connectTimeout=30'
        ports:
        - '80:8080'
        - '443:8443'
        volumes:
        - data-keycloak:/var/lib/keycloak
        networks:
        - leanda-ext
        depends_on:
        - postgres

volumes:
    data-keycloak:
    data-pstgresql:

networks:
    leanda-ext:
        external:
            name: leanda-net
