#` This docker-compose is for running Leanda services

version: '3'

services:
    ui:
        restart: always
        container_name: ui
        image: leanda/ui:${TAG_VERSION-latest}
        environment:
        - IDENTITY_SERVER_URL=${IDENTITY_SERVER_URL}
        - CORE_API_URL=${CORE_API_URL}
        - BLOB_STORAGE_API_URL=${BLOB_STORAGE_API_URL}
        - IMAGING_URL=${IMAGING_URL}
        - SIGNALR_URL=${SIGNALR_URL}
        - METADATA_URL=${METADATA_URL}
        - PROXY_JSMOL_URL=${PROXY_JSMOL_URL}
        - KETCHER_URL=${KETCHER_URL}
        - REALM=${REALM}
        networks:
        - leanda-ext
        ports:
        - "5555:80"

    blob-storage-api:
        restart: always
        container_name: blob-storage-api
        image: leanda/blob-storage-webapi:${TAG_VERSION-latest}
        environment:
        - IDENTITY_SERVER_URL=${IDENTITY_SERVER_URL_UNESCAPED}
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - SWAGGER_BASEPATH=/blob/v1
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "18006:18006"

    # notification-service-processing:
    #     restart: always
    #     container_name: notification-service-processing
    #     image: docker.scidatasoft.com/notification-serivce-processing:${TAG_VERSION-latest}
    #     environment:
    #     - OSDR_LOG_FOLDER=/logs
    #     volumes:
    #     - ${OSDR_LOG_FOLDER}:/logs
    #     networks:
    #     - leanda-ext

    metadata-processing:
        restart: always
        container_name: metadata-processing
        image: leanda/metadata-processing:${TAG_VERSION-latest}
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_EVENT_STORE=ConnectTo=tcp://admin:changeit@eventstore:1113
        - OSDR_ES=http://elasticsearch:9200
        - SWAGGER_BASEPATH=/osdr/v1
        - OSDR_LOG_LEVEL=Warn
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11050:11050"

    indexing:
        restart: always
        container_name: indexing
        image: leanda/indexing:${TAG_VERSION-latest}
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_ES=http://elasticsearch:9200
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11090:11090"

    core-web-api:
        restart: always
        container_name: core-web-api
        image: leanda/core-web-api:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - IDENTITY_SERVER_URL=${IDENTITY_SERVER_URL_UNESCAPED}
        - OSDR_REDIS=redis
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_EVENT_STORE=ConnectTo=tcp://admin:changeit@eventstore:1113
        - OSDR_ES=http://elasticsearch:9200
        - SWAGGER_BASEPATH=/osdr/v1
        - OSDR_LOG_LEVEL=${OSDR_LOG_LEVEL}
        command: ./wait-for-it.sh rabbitmq:5672 -t 30 -- ./wait-for-it.sh keycloak:8080 -t 30 -- ./Sds.Osdr.WebApi
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "28611:18006"

    core-backend:
        restart: always
        container_name: core-backend
        image: leanda/core-backend:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_EVENT_STORE=ConnectTo=tcp://admin:changeit@eventstore:1113
        - OSDR_REDIS=redis
        command: ./wait-for-it.sh rabbitmq:5672 -t 30 -- ./Sds.Osdr.Domain.BackEnd
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11030:11030"

    core-frontend:
        restart: always
        container_name: core-frontend
        image: leanda/core-frontend:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_EVENT_STORE=ConnectTo=tcp://admin:changeit@eventstore:1113
        - OSDR_REDIS=redis
        command: ./wait-for-it.sh rabbitmq:5672 -t 30 -- ./Sds.Osdr.Domain.FrontEnd
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11020:11020"

    core-sagahost:
        restart: always
        container_name: core-sagahost
        image: leanda/core-sagahost:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        command: ./wait-for-it.sh rabbitmq:5672 -t 30 -- ./Sds.Osdr.Domain.SagaHost
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11010:11010"

    core-persistence:
        restart: always
        container_name: core-persistence
        image: leanda/core-persistence:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        command: ./wait-for-it.sh rabbitmq:5672 -t 30 -- ./Sds.Osdr.Persistence
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11000:11000"

    # ml-modeler:
    #     restart: always
    #     container_name: ml-modeler
    #     image: docker.scidatasoft.com/osdr-ml-modeler:${TAG_VERSION-latest}
    #     environment:
    #     - OSDR_LOG_FOLDER=/logs
    #     - OSDR_TEMP_FILES_FOLDER=/temp
    #     - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
    #     - OSDR_BLOB_SERVICE_TOKEN_URL=${IDENTITY_SERVER_URL_UNESCAPED}/protocol/openid-connect/token
    #     - OSDR_BLOB_SERVICE_URL=${BLOB_STORAGE_API_URL_UNESCAPED}
    #     - OSDR_ML_MODELER_CLIENT_SECRET=52461d3c-7f0b-4b72-a508-1e7febaacabb
    #     - OSDR_ML_MODELER_CLIENT_ID=osdr_ml_modeler
    #     - OSDR_RABBIT_MQ_ML_MODELER_MAX_THREADS_NUMBER=32
    #     - OSDR_RABBIT_MQ_ML_MODELER_PREFETCH_COUNT=32
    #     volumes:
    #     # TODO temporary hardcoded part
    #     - /home/logs:/logs/
    #     - /home/temp/ml_services:/temp/
    #     # - ${OSDR_LOG_FOLDER}:/logs
    #     # - ${OSDR_TEMP_FILES_FOLDER}:/temp
    #     networks:
    #     - leanda-ext
    #     depends_on:
    #     - blob-storage-api
    #     command: >
    #       /bin/bash -c "
    #         sleep 5;
    #         python ./model_trainer.py;
    #       "

    # ml-predictor:
    #     restart: always
    #     container_name: ml-predictor
    #     image: docker.scidatasoft.com/osdr-ml-predictor:${TAG_VERSION-latest}
    #     environment:
    #     - OSDR_LOG_FOLDER=/logs
    #     - OSDR_TEMP_FILES_FOLDER=/temp
    #     - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
    #     - OSDR_BLOB_SERVICE_TOKEN_URL=${IDENTITY_SERVER_URL_UNESCAPED}/protocol/openid-connect/token
    #     - OSDR_BLOB_SERVICE_URL=${BLOB_STORAGE_API_URL_UNESCAPED}
    #     - OSDR_ML_MODELER_CLIENT_SECRET=52461d3c-7f0b-4b72-a508-1e7febaacabb
    #     - OSDR_ML_MODELER_CLIENT_ID=osdr_ml_modeler
    #     - OSDR_RABBIT_MQ_ML_QUEUE_CREATE_PREDICTION_COMMAND=Sds.MachineLearning.Integration.Domain.Commands.PredictProperties
    #     - OSDR_RABBIT_MQ_ML_ECHANGE_PREDICTION_CREATED_EVENT=Sds.MachineLearning.Integration.Domain.Events.PropertiesPredicted
    #     - OSDR_RABBIT_MQ_ML_ECHANGE_PREDICTION_FAILED_EVENT=Sds.MachineLearning.Integration.Domain.Events.PropertiesPredictionFailed
    #     - OSDR_RABBIT_MQ_ML_ECHANGE_PREDICTION_REPORT_CREATED_EVENT=Sds.MachineLearning.Integration.Domain.Events.PropertiesPredictionReportCreated
    #     - OSDR_RABBIT_MQ_ML_PREDICTOR_MAX_THREADS_NUMBER=32
    #     - OSDR_RABBIT_MQ_ML_PREDICTOR_PREFETCH_COUNT=32
    #     volumes:
    #     # TODO temporary hardcoded part
    #     - /home/logs:/logs/
    #     - /home/temp/ml_services:/temp/
    #     # - ${OSDR_LOG_FOLDER}:/logs
    #     # - ${OSDR_TEMP_FILES_FOLDER}:/temp
    #     networks:
    #     - leanda-ext
    #     depends_on:
    #     - blob-storage-api
    #     command: >
    #       /bin/bash -c "
    #         sleep 5;
    #         python ./properties_predictor.py;
    #       "

    imaging:
        restart: always
        container_name: imaging
        image: leanda/imaging:${TAG_VERSION-latest}
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - QUEUE_PREFETCH_SIZE=9
        - EXECUTOR_THREAD_COUNT=3
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        - ${OSDR_TEMP_FILES_FOLDER}:/temp
        networks:
        - leanda-ext

    chemical-file-parser:
        restart: always
        container_name: chemical-file-parser
        image: leanda/chemical-file-parser:${TAG_VERSION-latest}
        #mem_limit: 512m
        environment:
        - TZ=EST
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - QUEUE_PREFETCH_SIZE=9
        - EXECUTOR_THREAD_COUNT=3
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        - ${OSDR_TEMP_FILES_FOLDER}:/temp
        networks:
        - leanda-ext
    
    reaction-parser:
        restart: always
        container_name: reaction-file-parser
        image: leanda/reaction-file-parser:${TAG_VERSION-latest}
        #mem_limit: 512m
        environment:
        - TZ=EST
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - QUEUE_PREFETCH_SIZE=9
        - EXECUTOR_THREAD_COUNT=3
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        - ${OSDR_TEMP_FILES_FOLDER}:/temp
        networks:
        - leanda-ext

    crystal-parser:
        restart: always
        container_name: crystal-file-parser
        image: leanda/crystal-file-parser:${TAG_VERSION-latest}
        #mem_limit: 512m
        environment:
        - TZ=EST
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - QUEUE_PREFETCH_SIZE=9
        - EXECUTOR_THREAD_COUNT=3
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        - ${OSDR_TEMP_FILES_FOLDER}:/temp
        networks:
        - leanda-ext

    spectra-parser:
        restart: always
        container_name: spectra-file-parser
        image: leanda/spectra-file-parser:${TAG_VERSION-latest}
        #mem_limit: 512m
        environment:
        - TZ=EST
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - QUEUE_PREFETCH_SIZE=9
        - EXECUTOR_THREAD_COUNT=3
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        - ${OSDR_TEMP_FILES_FOLDER}:/temp
        networks:
        - leanda-ext

    # ml-training-reporter:
    #     restart: always
    #     container_name: ml-training-reporter
    #     image: docker.scidatasoft.com/osdr-ml-training-reporter:${TAG_VERSION-latest}
    #     #mem_limit: 1g
    #     environment:
    #     - OSDR_LOG_FOLDER=/logs
    #     - OSDR_TEMP_FILES_FOLDER=/temp
    #     - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
    #     - OSDR_BLOB_SERVICE_TOKEN_URL=${IDENTITY_SERVER_URL_UNESCAPED}/protocol/openid-connect/token
    #     - OSDR_BLOB_SERVICE_URL=${BLOB_STORAGE_API_URL_UNESCAPED}
    #     - OSDR_ML_MODELER_CLIENT_SECRET=52461d3c-7f0b-4b72-a508-1e7febaacabb
    #     - OSDR_ML_MODELER_CLIENT_ID=osdr_ml_modeler
    #     - OSDR_RABBIT_MQ_ML_TRAINING_REPORTER_MAX_THREADS_NUMBER=32
    #     - OSDR_RABBIT_MQ_ML_TRAINING_REPORTER_PREFETCH_COUNT=32
    #     - CORE_API_URL=${CORE_API_URL_UNESCAPED}
    #     volumes:
    #     # TODO temporary hardcoded part
    #     - /home/logs:/logs/
    #     - /home/temp/ml_services:/temp/
    #     # - ${OSDR_LOG_FOLDER}:/logs
    #     # - ${OSDR_TEMP_FILES_FOLDER}:/temp
    #     depends_on:
    #     - blob-storage-api
    #     networks:
    #     - leanda-ext
    #     command: >
    #       /bin/bash -c "
    #         sleep 5;
    #         python ./report_generator.py;
    #       "

    # ml-training-optimizer:
    #     restart: always
    #     container_name: ml-training-optimizer
    #     image: docker.scidatasoft.com/osdr-ml-training-optimizer:${TAG_VERSION-latest}
    #     #mem_limit: 1g
    #     environment:
    #     - OSDR_LOG_FOLDER=/logs
    #     - OSDR_TEMP_FILES_FOLDER=/temp
    #     - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
    #     - OSDR_BLOB_SERVICE_TOKEN_URL=${IDENTITY_SERVER_URL_UNESCAPED}/protocol/openid-connect/token
    #     - OSDR_BLOB_SERVICE_URL=${BLOB_STORAGE_API_URL_UNESCAPED}
    #     - OSDR_ML_MODELER_CLIENT_SECRET=52461d3c-7f0b-4b72-a508-1e7febaacabb
    #     - OSDR_ML_MODELER_CLIENT_ID=osdr_ml_modeler
    #     - OSDR_RABBIT_MQ_ML_TRAINING_OPTIMIZER_MAX_THREADS_NUMBER=32
    #     - OSDR_RABBIT_MQ_ML_TRAINING_OPTIMIZER_PREFETCH_COUNT=32
    #     volumes:
    #     # TODO temporary hardcoded part
    #     - /home/logs:/logs/
    #     - /home/temp/ml_services:/temp/
    #     # - ${OSDR_LOG_FOLDER}:/logs
    #     # - ${OSDR_TEMP_FILES_FOLDER}:/temp
    #     depends_on:
    #     - blob-storage-api
    #     networks:
    #     - leanda-ext
    #     command: >
    #       /bin/bash -c "
    #         sleep 5;
    #         python ./optimizer.py;
    #       "

    # ml-single-structure-predictor:
    #     restart: always
    #     container_name: ml-single-structure-predictor
    #     image: docker.scidatasoft.com/osdr-ml-single-structure-predictor:${TAG_VERSION-latest}
    #     #mem_limit: 36g
    #     environment:
    #     - OSDR_LOG_FOLDER=/logs
    #     - OSDR_TEMP_FILES_FOLDER=/temp
    #     - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
    #     - OSDR_BLOB_SERVICE_TOKEN_URL=${IDENTITY_SERVER_URL_UNESCAPED}/protocol/openid-connect/token
    #     - OSDR_BLOB_SERVICE_URL=${BLOB_STORAGE_API_URL_UNESCAPED}
    #     - OSDR_ML_MODELER_CLIENT_SECRET=52461d3c-7f0b-4b72-a508-1e7febaacabb
    #     - OSDR_ML_MODELER_CLIENT_ID=osdr_ml_modeler
    #     - OSDR_RABBIT_MQ_ML_SINGLE_STRUCTURE_PREDICTOR_MAX_THREADS_NUMBER=32
    #     - OSDR_RABBIT_MQ_ML_SINGLE_STRUCTURE_PREDICTOR_PREFETCH_COUNT=32
    #     - API_MODELS_ENTITIES_URL=${CORE_API_URL_UNESCAPED}/entities/models/public
    #     volumes:
    #     # TODO temporary hardcoded part
    #     - /home/logs:/logs/
    #     - /home/temp/ml_services:/temp/
    #     # - ${OSDR_LOG_FOLDER}:/logs
    #     # - ${OSDR_TEMP_FILES_FOLDER}:/temp
    #     depends_on:
    #     - blob-storage-api
    #     networks:
    #     - leanda-ext
    #     command: >
    #       /bin/bash -c "
    #         sleep 5;
    #         python ./single_structure_predictor.py;
    #       "

    # feature-vectors-calculator:
    #     restart: always
    #     container_name: feature-vectors-calculator
    #     image: docker.scidatasoft.com/osdr-feature-vectors-calculator:${TAG_VERSION-latest}
    #     #mem_limit: 1g
    #     environment:
    #     - OSDR_LOG_FOLDER=/logs
    #     - OSDR_TEMP_FILES_FOLDER=/temp
    #     - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
    #     - OSDR_RABBIT_MQ_FEATURE_VECTOR_CALCULATOR_MAX_THREADS_NUMBER=32
    #     - OSDR_RABBIT_MQ_FEATURE_VECTOR_CALCULATOR_PREFETCH_COUNT=32
    #     - REDIS_EXPIRATION_TIME_SECONDS=43200
    #     volumes:
    #     # TODO temporary hardcoded part
    #     - /home/logs:/logs/
    #     - /home/temp/ml_services:/temp/
    #     # - ${OSDR_LOG_FOLDER}:/logs
    #     # - ${OSDR_TEMP_FILES_FOLDER}:/temp
    #     networks:
    #     - leanda-ext
    #     command: >
    #       /bin/bash -c "
    #         sleep 5;
    #         python ./calculator.py;
    #       "

    office-processor:
        restart: always
        container_name: office-processor
        image: leanda/office-file-processor:${TAG_VERSION-latest}
        #mem_limit: 512m
        environment:
        - TZ=EST
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - QUEUE_PREFETCH_SIZE=9
        - EXECUTOR_THREAD_COUNT=2
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        - ${OSDR_TEMP_FILES_FOLDER}:/temp
        ports:
        - 8987:8087
        networks:
        - leanda-ext

    chemical-properties:
        restart: always
        container_name: chemical-properties
        image: leanda/chemical-properties:${TAG_VERSION-latest}
        #mem_limit: 512m
        environment:
        - TZ=EST
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - QUEUE_PREFETCH_SIZE=9
        - EXECUTOR_THREAD_COUNT=3
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        - ${OSDR_TEMP_FILES_FOLDER}:/temp
        ports:
        - 8986:8086
        networks:
        - leanda-ext

    chemical-export:
        restart: always
        container_name: chemical-export
        image: leanda/chemical-export:${TAG_VERSION-latest}
        #mem_limit: 512m
        environment:
        - TZ=EST
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - QUEUE_PREFETCH_SIZE=9
        - EXECUTOR_THREAD_COUNT=3
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        - ${OSDR_TEMP_FILES_FOLDER}:/temp
        ports:
        - 8988:8088
        networks:
        - leanda-ext

    web-importer:
        container_name: web-importer
        image: leanda/web-importer:${TAG_VERSION-latest}
        environment:
        - TZ=EST
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_LOG_FOLDER=/logs
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - QUEUE_PREFETCH_SIZE=9
        - EXECUTOR_THREAD_COUNT=3
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        - ${OSDR_TEMP_FILES_FOLDER}:/temp
        build:
            context: .
        ports:
        - 8989:8089
        networks:
        - leanda-ext

networks:
    leanda-ext:
        external:
            name: leanda-net
