version: '3'

services:
    eventstore:
        image: eventstore/eventstore:release-4.0.2
        #mem_limit: 2g
        container_name: eventstore
        ports:
        - "2113:2113"
        - "1113:1113"
        environment:
        - RUN_PROJECTIONS = All
        volumes:
        - data-eventstore:/var/lib/eventstore
        networks:
        - leanda-ext

    redis:
        image: redis:4-alpine
        #mem_limit: 256m
        container_name: redis
        command: redis-server --appendonly yes
        ports:
        - "6379:6379"
        volumes:
        - data-redis:/data
        networks:
        - leanda-ext

    rabbitmq:
        image: leanda/rabbitmq
        #mem_limit: 2g
        container_name: rabbitmq
        hostname: "rabbitmq-dev"
        environment:
        - RABBITMQ_DEFAULT_VHOST=osdr_dev
        ports:
        - "8282:15672"
        - "5671:5671"
        - "5672:5672"
        volumes:
        - data-rabbitmq:/var/lib/rabbitmq
        networks:
        - leanda-ext

    mongo:
        image: mongo:3.6
        #mem_limit: 12g
        container_name: mongo
        ports:
        - "27017:27017"
        volumes:
        - data-mongo-config:/data/configdb
        - data-mongo-data:/data/db
        networks:
        - leanda-ext

    postgres:
      container_name: 'keycloak-postgres'
      image: postgres:10.6
      environment:
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
        POSTGRES_DATABASE: keycloak
        POSTGRES_ROOT_PASSWORD: keycloak
        pgdata: data-pstgresql
      ports:
      - '5432:5432'
      networks:
      - leanda-ext
      volumes:
      - data-pstgresql:/data

    keycloak:
        container_name: 'keycloak-server'
        image: leanda/keycloak:latest
        environment:
          DB_VENDOR: POSTGRES
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: keycloak
          POSTGRES_PORT_5432_TCP_ADDR: postgres
          POSTGRES_DATABASE: keycloak
          JDBC_PARAMS: 'connectTimeout=30'
        ports:
        - '8080:8080'
        - '8443:8443'
        volumes:
        - data-keycloak:/data
        networks:
        - leanda-ext
        depends_on:
        - postgres

    # filebeat:
    #     image: docker.scidatasoft.com/filebeat
    #     #mem_limit: 128m
    #     container_name: filebeat
    #     volumes:
    #     - /home/logs:/logs/
    #     networks:
    #     - leanda-ext
    #     depends_on:
    #     - logstash

    # logstash:
    #     image: docker.scidatasoft.com/logstash
    #     #mem_limit: 1g
    #     container_name: logstash
    #     command: -f /config-dir/logstash.conf
    #     ports:
    #     - "5044:5044"
    #     - "12201:12201"
    #     - "12201:12201/udp"
    #     - "12202:12202"
    #     - "12202:12202/udp"
    #     networks:
    #     - leanda-ext
    #     depends_on:
    #     - elasticsearch

    # kibana:
    #     image: docker.elastic.co/kibana/kibana-oss:6.1.1
    #     #mem_limit: 512m
    #     container_name: kibana
    #     environment:
    #     - ELASTICSEARCH_URL:"elasticsearch:9201"
    #     ports:
    #     - "5661:5601"
    #     networks:
    #     - leanda-ext

    elasticsearch:
        image: leanda/elasticsearch
        #mem_limit: 10g
        container_name: elasticsearch
        environment:
        - discovery.type=single-node
        #- "ES_JAVA_OPTS=-Xms8g -Xmx8g"
        volumes:
        - data-elasticsearch:/usr/share/elasticsearch/data
        ports:
        - "9201:9201"
        - "9200:9200"
        - "9301:9300"
        networks:
        - leanda-ext

    ui:
        container_name: ui
        image: leanda/ui:${TAG_VERSION-latest}
        environment:
        - IDENTITY_SERVER_URL=${IDENTITY_SERVER_URL}
        - CORE_API_URL=${CORE_API_URL}
        - BLOB_STORAGE_API_URL=${BLOB_STORAGE_API_URL}
        - IMAGING_URL=${IMAGING_URL}
        - SIGNALR_URL=${SIGNALR_URL}
        - METADATA_URL=${METADATA_URL}
        - PROXY_JSMOL_URL=${PROXY_JSMOL_URL}
        - KETCHER_URL=${KETCHER_URL}
        - REALM=${REALM}
        # command: usr/share/wait-for.sh -t 30 blob-storage-api:18006 core-web-api:18006 -- usr/share/setenv.sh && sleep 3 && nginx -g 'daemon off;'
        networks:
        - leanda-ext
        ports:
        - "5555:80"
        depends_on:
        - blob-storage-api
        - core-web-api

    blob-storage-api:
        container_name: blob-storage-api
        entrypoint: /bin/bash
        image: leanda/blob-storage-webapi:${TAG_VERSION-latest}
        environment:
        - IDENTITY_SERVER_URL=${IDENTITY_SERVER_URL_UNESCAPED}
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        # - SWAGGER_BASEPATH=/blob/v1
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.Storage.Blob.WebApi
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "18006:18006"
        depends_on:
        - rabbitmq
        - mongo

    metadata-processing:
        container_name: metadata-processing
        image: leanda/metadata-processing:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.MetadataStorage.Processing
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11050:11050"
        depends_on:
        - rabbitmq

    indexing:
        container_name: indexing
        image: leanda/indexing:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_ES=http://elasticsearch:9200
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.Indexing
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11090:11090"
        depends_on:
        - rabbitmq

    core-web-api:
        container_name: core-web-api
        image: leanda/core-web-api:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - IDENTITY_SERVER_URL=${IDENTITY_SERVER_URL_UNESCAPED}
        - OSDR_REDIS=redis
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_EVENT_STORE=ConnectTo=tcp://admin:changeit@eventstore:1113
        - OSDR_ES=http://elasticsearch:9200
        # - SWAGGER_BASEPATH=/osdr/v1
        - OSDR_LOG_LEVEL=${OSDR_LOG_LEVEL}
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.Osdr.WebApi
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "28611:18006"
        depends_on:
        - rabbitmq
        - eventstore
        - redis
        - mongo

    core-backend:
        container_name: core-backend
        image: leanda/core-backend:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_EVENT_STORE=ConnectTo=tcp://admin:changeit@eventstore:1113
        - OSDR_REDIS=redis
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.Osdr.Domain.BackEnd
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11030:11030"
        depends_on:
        - rabbitmq
        - eventstore
        - redis
        - mongo

    core-frontend:
        container_name: core-frontend
        image: leanda/core-frontend:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_EVENT_STORE=ConnectTo=tcp://admin:changeit@eventstore:1113
        - OSDR_REDIS=redis
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.Osdr.Domain.FrontEnd
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11020:11020"

    core-sagahost:
        container_name: core-sagahost
        image: leanda/core-sagahost:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.Osdr.Domain.SagaHost
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11010:11010"
        depends_on:
        - rabbitmq
        - mongo

    core-persistence:
        container_name: core-persistence
        image: leanda/core-persistence:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.Osdr.Persistence
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "11000:11000"
        depends_on:
        - rabbitmq
        - mongo

    imaging:
        container_name: imaging
        image: leanda/imaging:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - QUEUE_PREFETCH_SIZE=9
        - EXECUTOR_THREAD_COUNT=3
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- java -Djava.awt.headless=true -Xmx256m -XX:NativeMemoryTracking=summary -jar sds-imaging-service.jar
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        - ${OSDR_TEMP_FILES_FOLDER}:/temp
        networks:
        - leanda-ext
        depends_on:
        - rabbitmq
        - mongo

    office-processor:
        container_name: office-processor
        image: leanda/office-file-processor:${TAG_VERSION-latest}
        #mem_limit: 512m
        entrypoint: /bin/bash
        environment:
        - TZ=EST
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        - QUEUE_PREFETCH_SIZE=9
        - EXECUTOR_THREAD_COUNT=2
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./wait-for-it.sh mongo:27017 -t 60 -- java -XX:NativeMemoryTracking=summary -jar office-file-processor.jar
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        - ${OSDR_TEMP_FILES_FOLDER}:/temp
        ports:
        - 8987:8087
        networks:
        - leanda-ext
        depends_on:
        - rabbitmq
        - mongo

volumes:
    data-eventstore:
    data-redis:
    data-rabbitmq:
    data-elasticsearch:
    data-mongo-config:
    data-mongo-data:
    data-pstgresql:
    data-keycloak:

networks:
    leanda-ext:
        external:
            name: leanda-net
