version: '3'

services:
    postgres:
      container_name: 'keycloak-postgres'
      image: postgres:10.6
      environment:
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
        POSTGRES_DATABASE: keycloak
        POSTGRES_ROOT_PASSWORD: keycloak
        pgdata: data-pstgresql
      ports:
      - '5432:5432'
      volumes:
      - data-pstgresql:/data

    keycloak:
        container_name: 'keycloak-server'
        image: leanda/keycloak:latest
        environment:
          DB_VENDOR: POSTGRES
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: keycloak
          POSTGRES_PORT_5432_TCP_ADDR: postgres
          POSTGRES_DATABASE: keycloak
          JDBC_PARAMS: 'connectTimeout=30'
        ports:
        - '8080:8080'
        - '8443:8443'
        volumes:
        - data-keycloak:/data
        depends_on:
        - postgres

volumes:
    data-eventstore:
    data-redis:
    data-rabbitmq:
    data-elasticsearch:
    data-mongo-config:
    data-mongo-data:
    data-keycloak:
    data-pstgresql:
