version: '3'

services:


    redis:
        image: redis:4-alpine
        command: redis-server --appendonly yes
        ports:
        - "6379:6379"
        volumes:
        - data-redis:/data
        logging:
            driver: awslogs
            options: 
                awslogs-group: ${AWS_LOG_GROUP}
                awslogs-region: ${AWS_REGION}
                awslogs-stream-prefix: redis


volumes:
    # data-eventstore:
    data-redis:
    # data-rabbitmq:
   #data-elasticsearch:
# #     data-mongo-config:
# #     data-mongo-data:
# #     data-pstgresql:
