version: '3'

services:
    redis:
        image: redis:4-alpine
        #mem_limit: 256m
        # restart: always
        container_name: redis
        command: redis-server --appendonly yes
        ports:
        - "6379:6379"
        volumes:
        - data-redis:/data
        networks:
        - leanda-ext

    rabbitmq:
        image: leanda/rabbitmq
        #mem_limit: 2g
        # restart: always
        container_name: rabbitmq
        hostname: "rabbitmq-dev"
        environment:
        - RABBITMQ_DEFAULT_VHOST=osdr_dev
        ports:
        - "8282:15672"
        - "5671:5671"
        - "5672:5672"
        volumes:
        - data-rabbitmq:/var/lib/rabbitmq
        networks:
        - leanda-ext

    # mongo:
    #     image: mongo:3.6
    #     #mem_limit: 12g
    #     # restart: always
    #     container_name: mongo
    #     ports:
    #     - "27017:27017"
    #     volumes:
    #     - data-mongo-config:/data/configdb
    #     - data-mongo-data:/data/db
    #     networks:
    #     - leanda-ext

    nginx:
        image: leanda/nginx
        container_name: nginx
        ports:
        - "80:80"
        networks:
        - leanda-ext
        depends_on:
        - blob-storage-api
        - core-web-api

    ui:
        container_name: ui
        image: leanda/ui:${TAG_VERSION-latest}
        environment:
        - IDENTITY_SERVER_URL=${IDENTITY_SERVER_URL}
        - CORE_API_URL=${CORE_API_URL}
        - BLOB_STORAGE_API_URL=${BLOB_STORAGE_API_URL}
        - IMAGING_URL=${IMAGING_URL}
        - SIGNALR_URL=${SIGNALR_URL}
        - METADATA_URL=${METADATA_URL}
        - PROXY_JSMOL_URL=${PROXY_JSMOL_URL}
        - KETCHER_URL=${KETCHER_URL}
        - REALM=${REALM}
        # command: usr/share/wait-for.sh -t 30 blob-storage-api:18006 core-web-api:18006 -- usr/share/setenv.sh && sleep 3 && nginx -g 'daemon off;'
        networks:
        - leanda-ext
        ports:
        - "5555:80"
        depends_on:
        - blob-storage-api
        - core-web-api

    core-web-api:
        # restart: always
        container_name: core-web-api
        image: leanda/core-web-api:${TAG_VERSION-latest}
        entrypoint: /bin/bash
        environment:
        - IDENTITY_SERVER_URL=${IDENTITY_SERVER_URL}
        - OSDR_REDIS=redis
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_EVENT_STORE=ConnectTo=tcp://admin:changeit@eventstore:1113
        - OSDR_ES=http://elasticsearch:9200
        # - SWAGGER_BASEPATH=/osdr/v1
        - OSDR_LOG_LEVEL=${OSDR_LOG_LEVEL}
        command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.Osdr.WebApi
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        networks:
        - leanda-ext
        ports:
        - "28611:18006"
        depends_on:
        - rabbitmq
        - eventstore
        - redis
        - mongo

    feature-vectors-calculator:
        # restart: always
        container_name: feature-vectors-calculator
        image: leanda/ml-feature-vectors-calculator:${TAG_VERSION-latest}
        #mem_limit: 1g
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_RABBIT_MQ_FEATURE_VECTOR_CALCULATOR_MAX_THREADS_NUMBER=32
        - OSDR_RABBIT_MQ_FEATURE_VECTOR_CALCULATOR_PREFETCH_COUNT=32
        - REDIS_EXPIRATION_TIME_SECONDS=43200
        - OSDR_ML_MODELER_CLIENT_ID=${OSDR_ML_MODELER_CLIENT_ID}
        - OSDR_ML_MODELER_CLIENT_SECRET=${OSDR_ML_MODELER_CLIENT_SECRET}
        - OSDR_BLOB_SERVICE_TOKEN_URL=${OSDR_BLOB_SERVICE_TOKEN_URL}
        - OSDR_BLOB_SERVICE_URL=${OSDR_BLOB_SERVICE_URL}
        - OSDR_API_URL=${CORE_API_URL}
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs
        - ${OSDR_TEMP_FILES_FOLDER}:/temp
        networks:
        - leanda-ext
        command: >
          /bin/bash -c "
            sleep 5;
            python ./calculator.py;
          "

volumes:
    data-redis:
    data-rabbitmq:
    # data-mongo-config:
    # data-mongo-data:

networks:
    leanda-ext:
        external:
            name: leanda-net
